(function(global){
'use strict';
const node=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n;};
const button=(text,fn,cls)=>{const b=node('button',cls,text);b.type='button';b.onclick=fn;return b;};
function mount(api,store){
 const root=api.root;let all=[],filtered=[],selected=new Set(),selecting=false,dead=false,frame=0,cols=3,step=110,epoch=0,filter='all',search='',viewerClose=null,lastRendered='',metadataVersion=0,loading=false,refreshAgain=false,albumId='',albumList=[];
 const nav=node('header','photo-nav'),select=button('Select',()=>{selecting=!selecting;if(!selecting)selected.clear();lastRendered='';render();}),heading=node('h1',null,'Photos'),picker=node('input');picker.type='file';picker.multiple=true;picker.accept='image/*,video/*,.heic,.heif';picker.hidden=true;
 const add=button('+',()=>picker.click(),'photo-add');add.setAttribute('aria-label','Add photos and videos');nav.append(select,heading,add);root.append(nav,picker);
 const tools=node('div','photo-tools'),query=node('input');query.type='search';query.placeholder='Search filenames';query.setAttribute('aria-label','Search photos');
 const types=node('select');types.setAttribute('aria-label','Media type');[['all','All media'],['image','Photos'],['video','Videos']].forEach(([v,t])=>{const o=node('option',null,t);o.value=v;types.append(o);});tools.append(query,types);root.append(tools);
 const albumTools=node('div','photo-tools album-tools'),albumPicker=node('select');albumPicker.setAttribute('aria-label','Album');albumTools.append(albumPicker,button('New album',()=>albumDialog(false)));root.append(albumTools);
 albumPicker.onchange=()=>{albumId=albumPicker.value;selected.clear();applyFilter();};
 function renderAlbums(){albumPicker.textContent='';[['','All media'],['unfiled','Unfiled'],...albumList.map(a=>[a.id,a.name])].forEach(([id,name])=>{const o=node('option',null,name);o.value=id;albumPicker.append(o);});albumPicker.value=albumId;}
 function albumDialog(moving){
  const d=node('dialog','album-dialog'),h=node('h2',null,moving?'Move to album':'New album'),name=node('input'),dest=node('select'),error=node('p');name.placeholder='Album name';name.maxLength=100;name.setAttribute('aria-label','New album name');error.setAttribute('role','alert');
  if(moving){[['','Unfiled'],...albumList.map(a=>[a.id,a.name])].forEach(([id,n])=>{const o=node('option',null,n);o.value=id;dest.append(o);});dest.setAttribute('aria-label','Destination album');}
  const commit=button(moving?'Move':'Create',async()=>{commit.disabled=true;try{let target=dest.value;if(name.value.trim()){const a=await store.createAlbum(name.value);target=a.id;}else if(!moving)throw new Error('Enter an album name.');if(moving)await store.move([...selected],target);else albumId=target;selected.clear();await refresh();d.close();}catch(e){error.textContent=e.message;}finally{commit.disabled=false;}});
  d.append(h);if(moving)d.append(dest,node('p',null,'Or create a new album:'));d.append(name,error,commit,button('Cancel',()=>d.close()));d.onclose=()=>d.remove();root.append(d);d.showModal();(moving?dest:name).focus();
 }
 const progress=node('section','import-panel');progress.hidden=true;const status=node('p');status.setAttribute('role','status');status.setAttribute('aria-live','polite');const meter=node('progress');const cancel=button('Stop import',()=>store.cancel()),retry=button('Retry failed files',()=>store.retry()),report=button('Download report',()=>download(new Blob([JSON.stringify(store.state,null,2)],{type:'application/json'}),'import-report.json'));
 progress.append(status,meter,cancel,retry,report);root.append(progress);
 const count=node('div','photo-count','Loading your library…');root.append(count);
 const scroller=node('div','photo-scroll');scroller.tabIndex=0;scroller.setAttribute('aria-label','Photo library');const canvas=node('div','photo-canvas');scroller.append(canvas);root.append(scroller);
 const empty=node('div','photo-empty');empty.hidden=true;empty.append(node('h2',null,'Your library, at full quality'),node('p',null,'Add photos and videos. Originals stay unchanged; small previews keep browsing fast.'),button('Add photos or videos',()=>picker.click()));scroller.append(empty);
 const bar=node('div','selection-bar');bar.hidden=true;const selectAll=button('Select all',()=>{selected=new Set(filtered.map(x=>x.id));lastRendered='';render();}),clear=button('Clear',()=>{selected.clear();lastRendered='';render();}),trash=button('Delete',removeSelected,'danger');let exporting=false,exportCancelled=false;const exportButton=button('Export',async()=>{
  if(exporting){exportCancelled=true;return;}if(!selected.size)return;exporting=true;exportCancelled=false;exportButton.textContent='Cancel export';selectAll.disabled=clear.disabled=trash.disabled=select.disabled=true;
  try{const ids=[...selected],progress=(n,total)=>{count.textContent='Exporting originals · '+n+' of '+total;};if(global.showDirectoryPicker){const handle=await global.showDirectoryPicker({mode:'readwrite'});await global.LoftExport.folder(handle,store,ids,progress,()=>exportCancelled||dead);api.toast('Original files saved to your selected folder.');}else{const blob=await global.LoftExport.zip(store,ids,progress,()=>exportCancelled||dead);download(blob,'Loft-originals.zip');api.toast('Originals exported in one ZIP.');}}catch(e){if(e.name!=='AbortError'){status.textContent=e.message;progress.hidden=false;meter.hidden=cancel.hidden=retry.hidden=report.hidden=true;}}finally{exporting=false;exportButton.textContent='Export';selectAll.disabled=clear.disabled=trash.disabled=select.disabled=false;lastRendered='';render();}
 },'accent');const moveButton=button('Move to Album',()=>albumDialog(true));bar.append(selectAll,clear,moveButton,exportButton,trash);root.append(bar);
 const slots=new Map(),previewCache=new Map();let cacheBytes=0,lastScroll=0,direction=1;let queue=[],busy=0;const previewFailures=new Set();
 function free(slot){slot.active=false;slot.el.remove();}
 function cached(id){const c=previewCache.get(id);if(c){previewCache.delete(id);previewCache.set(id,c);}return c;}
 function cache(id,blob){let c=cached(id);if(c)return c;c={url:URL.createObjectURL(blob),size:blob.size};previewCache.set(id,c);cacheBytes+=c.size;
  for(const [key,v] of previewCache){if(previewCache.size<=160&&cacheBytes<16*1048576)break;if(slots.has(key))continue;URL.revokeObjectURL(v.url);previewCache.delete(key);cacheBytes-=v.size;}return c;}
 function paint(slot,c){if(!slot.active||dead)return;const img=node('img');img.alt='';img.decoding='async';img.src=c.url;slot.el.prepend(img);slot.label.textContent=slot.meta.kind==='video'?'▶':'';}
 function priority(s){const top=s.index*step/cols,y=scroller.scrollTop,h=scroller.clientHeight||600;if(top+step>y&&top<y+h)return Math.abs(top-y)/100000;return (direction>0?top>=y+h:top<y)?1+Math.abs(top-y)/100000:2+Math.abs(top-y)/100000;}

 function schedule(){if(!frame)frame=requestAnimationFrame(()=>{frame=0;render();});}
 function applyFilter(){const q=search.trim().toLowerCase();filtered=all.filter(m=>(!albumId||(albumId==='unfiled'?!m.albumId:m.albumId===albumId))&&(filter==='all'||m.kind===filter)&&(!q||m.name.toLowerCase().includes(q)));scroller.scrollTop=0;metadataVersion++;lastRendered='';render();}
 let searchTimer;query.oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{search=query.value;applyFilter();},120);};types.onchange=()=>{filter=types.value;applyFilter();};
 async function refresh(){if(loading){refreshAgain=true;return;}loading=true;try{const y=scroller.scrollTop;[all,albumList]=await Promise.all([store.scan(),store.albums()]);all.sort((a,b)=>((b.createdAt||b.addedAt||0)-(a.createdAt||a.addedAt||0))||a.id.localeCompare(b.id));if(dead)return;const ids=new Set(all.map(m=>m.id));selected=new Set([...selected].filter(id=>ids.has(id)));renderAlbums();applyFilter();scroller.scrollTop=y;schedule();}catch(e){count.textContent=e.message;}finally{loading=false;if(refreshAgain&&!dead){refreshAgain=false;refresh();}}}
 function render(){
  if(dead)return;cols=Math.max(3,Math.min(8,Math.floor((scroller.clientWidth||360)/112)));step=(scroller.clientWidth||360)/cols;
  direction=scroller.scrollTop===lastScroll?direction:scroller.scrollTop>lastScroll?1:-1;lastScroll=scroller.scrollTop;const totalRows=Math.ceil(filtered.length/cols),visible=Math.floor(scroller.scrollTop/step),first=Math.max(0,visible-(direction<0?4:1)),end=Math.min(totalRows,visible+Math.ceil((scroller.clientHeight||600)/step)+(direction>0?4:1));
  canvas.style.height=totalRows*step+'px';if(!exporting)count.textContent=selecting?selected.size.toLocaleString()+' selected':filtered.length.toLocaleString()+' items · Originals preserved';select.textContent=selecting?'Done':'Select';bar.hidden=!selecting;moveButton.disabled=exporting||!selected.size;trash.disabled=exporting||!selected.size;exportButton.disabled=!exporting&&!selected.size;selectAll.textContent='Select all ('+filtered.length.toLocaleString()+')';empty.hidden=filtered.length>0;
  if(!all.length){empty.querySelector('h2').textContent='Your library, at full quality';}else if(!filtered.length){empty.querySelector('h2').textContent='No matching photos or videos';}
  const signature=[first,end,cols,step,selecting,metadataVersion,selected.size].join(':');if(signature===lastRendered)return;lastRendered=signature;
  const wanted=new Set();for(let i=first*cols;i<Math.min(end*cols,filtered.length);i++)wanted.add(filtered[i].id);
  slots.forEach((s,id)=>{if(!wanted.has(id)){free(s);slots.delete(id);}});
  for(let i=first*cols;i<Math.min(end*cols,filtered.length);i++){
   const m=filtered[i];let slot=slots.get(m.id);
   if(!slot){const b=button('',()=>selecting?toggle(m.id):view(m.id),'media-tile');b.setAttribute('aria-label',m.name);const label=node('span','media-label',m.kind==='video'?'▶ Video':'Photo');b.append(label);slot={el:b,label,active:true,meta:m,url:null};slots.set(m.id,slot);canvas.append(b);const hit=cached(m.id);if(hit)paint(slot,hit);else queue.push(slot);
    b.oncontextmenu=e=>{e.preventDefault();selecting=true;selected.add(m.id);lastRendered='';render();};
   }
   slot.index=i;slot.el.style.cssText='position:absolute;left:'+((i%cols)*step)+'px;top:'+(Math.floor(i/cols)*step)+'px;width:'+(step-3)+'px;height:'+(step-3)+'px';slot.el.classList.toggle('selected',selected.has(m.id));slot.el.setAttribute('aria-pressed',String(selected.has(m.id)));slot.el.classList.toggle('selecting',selecting);
  }
  queue=queue.filter(s=>s.active).sort((a,b)=>priority(a)-priority(b));pump();
 }
 function toggle(id){selected.has(id)?selected.delete(id):selected.add(id);lastRendered='';render();}
 async function pump(){while(busy<4&&queue.length&&!dead){queue.sort((a,b)=>priority(a)-priority(b));const s=queue.shift();if(!s.active)continue;busy++;(async()=>{try{
   const hit=cached(s.meta.id);if(hit){paint(s,hit);return;}
   const r=await store.get(s.meta.id);if(!r||!s.active||dead)return;let thumb=r.thumb;
   if(!thumb&&!previewFailures.has(r.id)){thumb=await makePreview(r.blob,r.kind);if(thumb&&!dead)await store.thumbnail(r.id,thumb);else previewFailures.add(r.id);}
   if(thumb&&!dead)paint(s,cache(r.id,thumb));else if(s.active)s.label.textContent=r.name+' · Open original';
  }catch(e){if(s.active)s.label.textContent='Preview unavailable';}finally{busy--;pump();}})();}}
 async function removeSelected(){const ids=Array.from(selected);if(!ids.length||!confirm('Delete '+ids.length+' items from this device? Synced items move to cloud Trash on the next sync. Items never synced have no cloud recovery.'))return;
  trash.disabled=true;selectAll.disabled=true;select.disabled=true;try{await store.remove(ids,n=>{count.textContent='Deleting '+n+' of '+ids.length;});selected.clear();await refresh();api.toast('Items deleted');}catch(e){api.toast('Deletion stopped: '+e.message);await refresh();}finally{trash.disabled=false;selectAll.disabled=false;select.disabled=false;}}
 let lastSaved=0;const unsubscribe=store.subscribe(s=>{if(dead)return;progress.hidden=false;status.textContent=s.error||[s.running?'Importing':'Import finished',s.processed+' of '+s.total+' checked',s.saved+' saved',s.duplicates+' duplicates skipped',s.failed.length+' failed',s.cancelled?'Stopped. Reselect the remaining files to continue.':''].filter(Boolean).join(' · ');meter.max=s.total||1;meter.value=s.processed;meter.hidden=!s.running;cancel.hidden=!s.running;retry.hidden=s.running||!s.failed.length;report.hidden=s.running||!s.failed.length;add.disabled=s.running;if(s.saved-lastSaved>=100||!s.running){lastSaved=s.saved;refresh();}});
 picker.onchange=()=>{if(picker.files.length)store.importFiles(Array.from(picker.files),albumId&&albumId!=='unfiled'?albumId:null).catch(e=>api.toast(e.message));picker.value='';};
 store.lastJob().then(s=>{if(s&&s.running&&!store.state.running&&!dead){progress.hidden=false;status.textContent='A previous import was interrupted. '+s.saved+' files were saved. Reselect your batch to continue; exact duplicates are skipped.';meter.hidden=cancel.hidden=retry.hidden=report.hidden=true;}}).catch(()=>{});
 if(store.state.running){progress.hidden=false;status.textContent='Import in progress. '+store.state.saved+' files saved.';cancel.hidden=false;retry.hidden=report.hidden=true;add.disabled=true;}
 const changed=()=>{if(viewerClose)viewerClose();refresh();};global.addEventListener('loft-data-changed',changed);
 scroller.addEventListener('scroll',schedule,{passive:true});const ro=global.ResizeObserver?new ResizeObserver(()=>{lastRendered='';schedule();}):null;if(ro)ro.observe(scroller);refresh();
 function view(id){if(viewerClose)viewerClose();viewerClose=global.LoftViewer.open({parent:api.win,items:filtered.slice(),id,get:m=>store.get(m.id),download,toast:api.toast,onClose:()=>{viewerClose=null;if(!dead)select.focus();}});}
 return ()=>{dead=true;global.removeEventListener('loft-data-changed',changed);root.querySelectorAll('.album-dialog').forEach(d=>d.remove());epoch++;clearTimeout(searchTimer);cancelAnimationFrame(frame);unsubscribe();if(ro)ro.disconnect();if(viewerClose)viewerClose();slots.forEach(free);slots.clear();for(const c of previewCache.values())URL.revokeObjectURL(c.url);previewCache.clear();queue=[];};
}
function download(blob,name){const u=URL.createObjectURL(blob),a=node('a');a.href=u;a.download=name||'original';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),60000);}
function makePreview(blob,kind){return new Promise(resolve=>{let settled=false,u=URL.createObjectURL(blob),m=document.createElement(kind==='video'?'video':'img');const finish=b=>{if(settled)return;settled=true;clearTimeout(timer);m.onload=m.onerror=m.onloadeddata=m.onseeked=null;if(kind==='video'){m.pause();m.removeAttribute('src');m.load();}else m.removeAttribute('src');URL.revokeObjectURL(u);resolve(b);};const timer=setTimeout(()=>finish(null),4000);function draw(){try{const w=m.videoWidth||m.naturalWidth,h=m.videoHeight||m.naturalHeight;if(!w||!h)return finish(null);const c=document.createElement('canvas'),s=Math.min(1,320/Math.max(w,h));c.width=Math.max(1,Math.round(w*s));c.height=Math.max(1,Math.round(h*s));c.getContext('2d').drawImage(m,0,0,c.width,c.height);c.toBlob(finish,'image/jpeg',.8);}catch(e){finish(null);}}m.onerror=()=>finish(null);if(kind==='video'){m.muted=true;m.playsInline=true;m.preload='auto';m.onloadeddata=draw;}else{m.decoding='async';m.onload=draw;}if(kind!=='video'&&global.createImageBitmap){global.createImageBitmap(blob,{resizeWidth:320,resizeQuality:'low'}).then(bitmap=>{if(settled){bitmap.close();return;}try{const c=document.createElement('canvas');c.width=bitmap.width;c.height=bitmap.height;c.getContext('2d').drawImage(bitmap,0,0);bitmap.close();c.toBlob(finish,'image/jpeg',.8);}catch(e){bitmap.close();if(!settled)m.src=u;}}).catch(()=>{if(!settled)m.src=u;});}else m.src=u;});}
global.LoftPhotos={mount,makePreview};
})(window);
