(function(global){
'use strict';
const node=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n;};
const button=(text,fn,cls)=>{const b=node('button',cls,text);b.type='button';b.onclick=fn;return b;};
function mount(api,store){
 const root=api.root;let all=[],filtered=[],selected=new Set(),selecting=false,dead=false,frame=0,cols=3,step=110,epoch=0,filter='all',search='',viewerClose=null,lastRendered='',metadataVersion=0,loading=false,refreshAgain=false;
 const nav=node('header','photo-nav'),select=button('Select',()=>{selecting=!selecting;if(!selecting)selected.clear();lastRendered='';render();}),heading=node('h1',null,'Photos'),picker=node('input');picker.type='file';picker.multiple=true;picker.accept='image/*,video/*,.heic,.heif';picker.hidden=true;
 const add=button('+',()=>picker.click(),'photo-add');add.setAttribute('aria-label','Add photos and videos');nav.append(select,heading,add);root.append(nav,picker);
 const tools=node('div','photo-tools'),query=node('input');query.type='search';query.placeholder='Search filenames';query.setAttribute('aria-label','Search photos');
 const types=node('select');types.setAttribute('aria-label','Media type');[['all','All media'],['image','Photos'],['video','Videos']].forEach(([v,t])=>{const o=node('option',null,t);o.value=v;types.append(o);});tools.append(query,types);root.append(tools);
 const progress=node('section','import-panel');progress.hidden=true;const status=node('p');status.setAttribute('role','status');status.setAttribute('aria-live','polite');const meter=node('progress');const cancel=button('Stop import',()=>store.cancel()),retry=button('Retry failed files',()=>store.retry()),report=button('Download report',()=>download(new Blob([JSON.stringify(store.state,null,2)],{type:'application/json'}),'import-report.json'));
 progress.append(status,meter,cancel,retry,report);root.append(progress);
 const count=node('div','photo-count','Loading your library…');root.append(count);
 const scroller=node('div','photo-scroll');scroller.tabIndex=0;scroller.setAttribute('aria-label','Photo library');const canvas=node('div','photo-canvas');scroller.append(canvas);root.append(scroller);
 const empty=node('div','photo-empty');empty.hidden=true;empty.append(node('h2',null,'Your library, at full quality'),node('p',null,'Add photos and videos. Originals stay unchanged; small previews keep browsing fast.'),button('Add photos or videos',()=>picker.click()));scroller.append(empty);
 const bar=node('div','selection-bar');bar.hidden=true;const selectAll=button('Select all',()=>{selected=new Set(filtered.map(x=>x.id));lastRendered='';render();}),clear=button('Clear',()=>{selected.clear();lastRendered='';render();}),trash=button('Delete',removeSelected,'danger');let exporting=false,exportCancelled=false;const exportButton=button('Export',async()=>{
  if(exporting){exportCancelled=true;return;}if(!selected.size)return;exporting=true;exportCancelled=false;exportButton.textContent='Cancel export';selectAll.disabled=clear.disabled=trash.disabled=select.disabled=true;
  try{const ids=[...selected],progress=(n,total)=>{count.textContent='Exporting originals · '+n+' of '+total;};if(global.showDirectoryPicker){const handle=await global.showDirectoryPicker({mode:'readwrite'});await global.LoftExport.folder(handle,store,ids,progress,()=>exportCancelled||dead);api.toast('Original files saved to your selected folder.');}else{const blob=await global.LoftExport.zip(store,ids,progress,()=>exportCancelled||dead);download(blob,'Loft-originals.zip');api.toast('Originals exported in one ZIP.');}}catch(e){if(e.name!=='AbortError'){status.textContent=e.message;progress.hidden=false;meter.hidden=cancel.hidden=retry.hidden=report.hidden=true;}}finally{exporting=false;exportButton.textContent='Export';selectAll.disabled=clear.disabled=trash.disabled=select.disabled=false;lastRendered='';render();}
 },'accent');bar.append(selectAll,clear,exportButton,trash);root.append(bar);
 const slots=new Map();let queue=[],busy=0;const previewFailures=new Set();
 function free(slot){slot.active=false;if(slot.url)URL.revokeObjectURL(slot.url);slot.el.remove();}
 function schedule(){if(!frame)frame=requestAnimationFrame(()=>{frame=0;render();});}
 function applyFilter(){const q=search.trim().toLowerCase();filtered=all.filter(m=>(filter==='all'||m.kind===filter)&&(!q||m.name.toLowerCase().includes(q)));scroller.scrollTop=0;metadataVersion++;lastRendered='';render();}
 let searchTimer;query.oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{search=query.value;applyFilter();},120);};types.onchange=()=>{filter=types.value;applyFilter();};
 async function refresh(){if(loading){refreshAgain=true;return;}loading=true;try{all=await store.scan();all.sort((a,b)=>(b.createdAt||b.addedAt)-(a.createdAt||a.addedAt));if(dead)return;applyFilter();}catch(e){count.textContent=e.message;}finally{loading=false;if(refreshAgain&&!dead){refreshAgain=false;refresh();}}}
 function render(){
  if(dead)return;cols=Math.max(3,Math.min(8,Math.floor((scroller.clientWidth||360)/112)));step=(scroller.clientWidth||360)/cols;
  const totalRows=Math.ceil(filtered.length/cols),first=Math.max(0,Math.floor(scroller.scrollTop/step)-2),end=Math.min(totalRows,first+Math.ceil((scroller.clientHeight||600)/step)+5);
  canvas.style.height=totalRows*step+'px';if(!exporting)count.textContent=selecting?selected.size.toLocaleString()+' selected':filtered.length.toLocaleString()+' items · Originals preserved';select.textContent=selecting?'Done':'Select';bar.hidden=!selecting;trash.disabled=exporting||!selected.size;exportButton.disabled=!exporting&&!selected.size;selectAll.textContent='Select all ('+filtered.length.toLocaleString()+')';empty.hidden=filtered.length>0;
  if(!all.length){empty.querySelector('h2').textContent='Your library, at full quality';}else if(!filtered.length){empty.querySelector('h2').textContent='No matching photos or videos';}
  const signature=[first,end,cols,step,selecting,metadataVersion,selected.size].join(':');if(signature===lastRendered)return;lastRendered=signature;
  const wanted=new Set();for(let i=first*cols;i<Math.min(end*cols,filtered.length);i++)wanted.add(filtered[i].id);
  slots.forEach((s,id)=>{if(!wanted.has(id)){free(s);slots.delete(id);}});
  for(let i=first*cols;i<Math.min(end*cols,filtered.length);i++){
   const m=filtered[i];let slot=slots.get(m.id);
   if(!slot){const b=button('',()=>selecting?toggle(m.id):view(m.id),'media-tile');b.setAttribute('aria-label',m.name);const label=node('span','media-label',m.kind==='video'?'▶ Video':'Photo');b.append(label);slot={el:b,label,active:true,meta:m,url:null};slots.set(m.id,slot);canvas.append(b);queue.push(slot);
    b.oncontextmenu=e=>{e.preventDefault();selecting=true;selected.add(m.id);lastRendered='';render();};
   }
   slot.el.style.cssText='position:absolute;left:'+((i%cols)*step)+'px;top:'+(Math.floor(i/cols)*step)+'px;width:'+(step-3)+'px;height:'+(step-3)+'px';slot.el.classList.toggle('selected',selected.has(m.id));slot.el.setAttribute('aria-pressed',String(selected.has(m.id)));slot.el.classList.toggle('selecting',selecting);
  }
  queue=queue.filter(s=>s.active);pump();
 }
 function toggle(id){selected.has(id)?selected.delete(id):selected.add(id);lastRendered='';render();}
 async function pump(){while(busy<2&&queue.length&&!dead){const s=queue.shift();if(!s.active)continue;busy++;(async()=>{try{const r=await store.get(s.meta.id);if(!r||!s.active||dead)return;let thumb=r.thumb;
    if(!thumb&&!previewFailures.has(r.id)){try{thumb=await makePreview(r.blob,r.kind);if(thumb&&!dead&&s.active)await store.thumbnail(r.id,thumb);else previewFailures.add(r.id);}catch(e){previewFailures.add(r.id);}}
    if(thumb&&s.active&&!dead){const img=node('img');img.alt='';img.decoding='async';s.url=URL.createObjectURL(thumb);img.src=s.url;s.el.prepend(img);s.label.textContent=r.kind==='video'?'▶':'';}else if(s.active){s.label.textContent=r.name+' · Open original';}
   }catch(e){if(s.active)s.label.textContent='Preview unavailable';}finally{busy--;pump();}})();}}
 async function removeSelected(){const ids=Array.from(selected);if(!ids.length||!confirm('Delete '+ids.length+' items from this device? Synced items move to cloud Trash on the next sync. Items never synced have no cloud recovery.'))return;
  trash.disabled=true;selectAll.disabled=true;select.disabled=true;try{await store.remove(ids,n=>{count.textContent='Deleting '+n+' of '+ids.length;});selected.clear();await refresh();api.toast('Items deleted');}catch(e){api.toast('Deletion stopped: '+e.message);await refresh();}finally{trash.disabled=false;selectAll.disabled=false;select.disabled=false;}}
 let lastSaved=0;const unsubscribe=store.subscribe(s=>{if(dead)return;progress.hidden=false;status.textContent=s.error||[s.running?'Importing':'Import finished',s.processed+' of '+s.total+' checked',s.saved+' saved',s.duplicates+' duplicates skipped',s.failed.length+' failed',s.cancelled?'Stopped. Reselect the remaining files to continue.':''].filter(Boolean).join(' · ');meter.max=s.total||1;meter.value=s.processed;meter.hidden=!s.running;cancel.hidden=!s.running;retry.hidden=s.running||!s.failed.length;report.hidden=s.running||!s.failed.length;add.disabled=s.running;if(s.saved-lastSaved>=100||!s.running){lastSaved=s.saved;refresh();}});
 picker.onchange=()=>{if(picker.files.length)store.importFiles(Array.from(picker.files)).catch(e=>api.toast(e.message));picker.value='';};
 store.lastJob().then(s=>{if(s&&s.running&&!store.state.running&&!dead){progress.hidden=false;status.textContent='A previous import was interrupted. '+s.saved+' files were saved. Reselect your batch to continue; exact duplicates are skipped.';meter.hidden=cancel.hidden=retry.hidden=report.hidden=true;}}).catch(()=>{});
 if(store.state.running){progress.hidden=false;status.textContent='Import in progress. '+store.state.saved+' files saved.';cancel.hidden=false;retry.hidden=report.hidden=true;add.disabled=true;}
 scroller.addEventListener('scroll',schedule,{passive:true});const ro=global.ResizeObserver?new ResizeObserver(()=>{lastRendered='';schedule();}):null;if(ro)ro.observe(scroller);refresh();
 async function view(id){
  if(viewerClose)viewerClose();let index=filtered.findIndex(m=>m.id===id),token=0,src=null,record=null,scale=1,pointers=new Map(),distance=0,baseScale=1,dx=0,dy=0,panStart=null,swipe=null;
  const v=node('div','media-viewer viewer');v.setAttribute('role','dialog');v.setAttribute('aria-modal','true');v.setAttribute('aria-label','Media viewer');const top=node('header','viewer-nav'),back=button('Done',close),title=node('div','viewer-title'),save=button('Download',()=>record&&download(record.blob,record.name));top.append(back,title,save);
  const area=node('div','media-stage'),footer=node('footer','viewer-actions'),prev=button('‹ Previous',()=>show(index-1)),next=button('Next ›',()=>show(index+1)),zoom=button('Zoom',()=>{scale=scale===1?2:1;dx=dy=0;transform();}),share=button('Share',async()=>{if(!record)return;const f=new File([record.blob],record.name,{type:record.type});try{if(navigator.canShare&&navigator.canShare({files:[f]}))await navigator.share({files:[f]});else download(record.blob,record.name);}catch(e){if(e.name!=='AbortError')api.toast('Sharing unavailable. Use Download.');}});footer.append(prev,zoom,share,next);v.append(top,area,footer);api.win.append(v);back.focus();
  let img=null;
  function transform(){if(img)img.style.transform='translate('+dx+'px,'+dy+'px) scale('+scale+')';zoom.textContent=scale===1?'Zoom':'Reset zoom';}
  function clear(){const video=area.querySelector('video');if(video){video.pause();video.removeAttribute('src');video.load();}if(src)URL.revokeObjectURL(src);src=null;area.textContent='';img=null;pointers.clear();scale=1;dx=dy=0;}
  async function show(i){if(i<0||i>=filtered.length)return;index=i;const request=++token;clear();record=null;prev.disabled=i===0;next.disabled=i===filtered.length-1;save.disabled=share.disabled=true;title.textContent=filtered[i].name;area.append(node('p',null,'Opening original…'));
   try{const r=await store.get(filtered[i].id);if(request!==token)return;if(!r||!r.blob)throw new Error('This file is no longer on this device.');record=r;area.textContent='';src=URL.createObjectURL(r.blob);const media=node(r.kind==='video'?'video':'img');media.src=src;if(r.kind==='video'){media.controls=true;media.playsInline=true;media.preload='metadata';}else{img=media;media.alt=r.name;media.draggable=false;}zoom.hidden=r.kind==='video';area.classList.toggle('is-photo',r.kind!=='video');media.onerror=()=>{if(request===token){area.textContent='';area.append(node('p',null,'This browser cannot preview this format. Download the unchanged original to open it in another app.'));}};area.append(media);save.disabled=share.disabled=false;transform();
   }catch(e){if(request===token){area.textContent='';area.append(node('p',null,e.message));}}
  }
  area.onpointerdown=e=>{if(!img)return;area.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const [a,b]=[...pointers.values()];distance=Math.hypot(a.x-b.x,a.y-b.y);baseScale=scale;swipe=null;}else{swipe={x:e.clientX,y:e.clientY,t:Date.now()};panStart={x:e.clientX,y:e.clientY,dx,dy};}};
  area.onpointermove=e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const [a,b]=[...pointers.values()];scale=Math.max(1,Math.min(5,baseScale*Math.hypot(a.x-b.x,a.y-b.y)/Math.max(1,distance)));transform();}else if(scale>1&&panStart){dx=panStart.dx+e.clientX-panStart.x;dy=panStart.dy+e.clientY-panStart.y;transform();}};
  area.onpointerup=e=>{pointers.delete(e.pointerId);if(!pointers.size&&swipe&&scale===1){const x=e.clientX-swipe.x,y=e.clientY-swipe.y;if(Math.abs(x)>65&&Math.abs(x)>Math.abs(y)*1.6&&Date.now()-swipe.t<700)show(index+(x<0?1:-1));}swipe=null;panStart=null;};area.onpointercancel=()=>{pointers.clear();swipe=null;panStart=null;};area.ondblclick=()=>{if(img){scale=scale===1?2:1;dx=dy=0;transform();}};
  function keys(e){if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();close();}if(e.key==='ArrowLeft')show(index-1);if(e.key==='ArrowRight')show(index+1);if(e.key==='Tab'){const controls=[...v.querySelectorAll('button:not(:disabled),video')].filter(x=>!x.hidden);const first=controls[0],last=controls[controls.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}
  function close(){token++;clear();document.removeEventListener('keydown',keys,true);v.remove();viewerClose=null;if(!dead)select.focus();}
  viewerClose=close;v.addEventListener('closeviewer',close);document.addEventListener('keydown',keys,true);show(index);
 }
 return ()=>{dead=true;epoch++;clearTimeout(searchTimer);cancelAnimationFrame(frame);unsubscribe();if(ro)ro.disconnect();if(viewerClose)viewerClose();slots.forEach(free);slots.clear();queue=[];};
}
function download(blob,name){const u=URL.createObjectURL(blob),a=node('a');a.href=u;a.download=name||'original';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),60000);}
function makePreview(blob,kind){return new Promise(resolve=>{let settled=false,u=URL.createObjectURL(blob),m=document.createElement(kind==='video'?'video':'img');const finish=b=>{if(settled)return;settled=true;clearTimeout(timer);m.onload=m.onerror=m.onloadeddata=m.onseeked=null;if(kind==='video'){m.pause();m.removeAttribute('src');m.load();}else m.removeAttribute('src');URL.revokeObjectURL(u);resolve(b);};const timer=setTimeout(()=>finish(null),4000);function draw(){try{const w=m.videoWidth||m.naturalWidth,h=m.videoHeight||m.naturalHeight;if(!w||!h)return finish(null);const c=document.createElement('canvas'),s=Math.min(1,320/Math.max(w,h));c.width=Math.max(1,Math.round(w*s));c.height=Math.max(1,Math.round(h*s));c.getContext('2d').drawImage(m,0,0,c.width,c.height);c.toBlob(finish,'image/jpeg',.8);}catch(e){finish(null);}}m.onerror=()=>finish(null);if(kind==='video'){m.muted=true;m.playsInline=true;m.preload='auto';m.onloadeddata=draw;}else{m.decoding='async';m.onload=draw;}if(kind!=='video'&&global.createImageBitmap){global.createImageBitmap(blob,{resizeWidth:320,resizeQuality:'low'}).then(bitmap=>{if(settled){bitmap.close();return;}try{const c=document.createElement('canvas');c.width=bitmap.width;c.height=bitmap.height;c.getContext('2d').drawImage(bitmap,0,0);bitmap.close();c.toBlob(finish,'image/jpeg',.8);}catch(e){bitmap.close();if(!settled)m.src=u;}}).catch(()=>{if(!settled)m.src=u;});}else m.src=u;});}
global.LoftPhotos={mount,makePreview};
})(window);
