const {JSDOM}=require('jsdom'),{IDBFactory}=require('fake-indexeddb'),fs=require('fs'),assert=require('assert/strict'),{webcrypto}=require('crypto');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
 const html=fs.readFileSync('index.html','utf8'),dom=new JSDOM(html,{url:'https://loft.test',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;
 w.indexedDB=new IDBFactory();w.Blob=Blob;w.File=require('buffer').File;Object.defineProperty(w,'crypto',{value:webcrypto});w.matchMedia=()=>({matches:false,addEventListener(){}});w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};w.confirm=()=>true;w.fetch=async()=>new Response('{}');w.AbortSignal=AbortSignal;w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;
 let main;
 for(const script of [...w.document.scripts]){if(script.src)w.eval(fs.readFileSync(''+script.getAttribute('src'),'utf8'));else if(script.textContent.includes("var REG=")){main=script.textContent;main=main.replace(/\}\)\(\);\s*$/, "window.TEST={openApp,closeApp,DB,REG,mediaStore};})();");fs.writeFileSync('checks/redesign-inline.js',main);w.eval(main);}else w.eval(script.textContent);}
 await sleep(60);assert(w.TEST);const {openApp,closeApp,DB}=w.TEST;
 const click=text=>{const b=[...w.document.querySelectorAll('.appwin button')].find(b=>b.textContent===text);assert(b,'missing '+text);b.click();};
 openApp('notes');await sleep(30);click('New note');let ta=w.document.querySelector('.note-editor textarea');ta.value='A durable note\n- [ ] Todo\n**Bold**';ta.dispatchEvent(new w.Event('input'));closeApp(true);await sleep(50);let notes=await DB.all('notes');assert(notes.some(n=>n.text.startsWith('A durable note')),'close flushed edit');
 openApp('notes');await sleep(30);[...w.document.querySelectorAll('.note-card')].find(n=>n.textContent.includes('A durable')).click();click('Preview');assert.equal(w.document.querySelector('.note-preview strong').textContent,'Bold');const check=w.document.querySelector('.note-preview input');check.click();click('Delete');await sleep(30);assert(!(await DB.all('notes')).some(n=>n.text.startsWith('A durable')),'deleted note must not resurrect');closeApp(true);await sleep(25);
 openApp('phone');await sleep(40);for(const digit of ['1','2','3'])w.document.querySelector(`.kp-key[aria-label="${digit}"]`).click();assert.equal(w.document.querySelector('.kp-display .num').textContent,'123');w.document.querySelector('.kp-call').click();assert.equal(w.document.querySelector('.callscreen a').getAttribute('href'),'tel:123');assert(!w.document.querySelector('.cs').textContent.includes('calling'));closeApp(true);await sleep(25);
 openApp('messages');await sleep(40);w.document.querySelector('.messages .row').click();ta=w.document.querySelector('.composer textarea');ta.value='Draft survives navigation';ta.dispatchEvent(new w.Event('input'));await sleep(30);closeApp(true);openApp('messages');await sleep(30);w.document.querySelector('.messages .row').click();assert.equal(w.document.querySelector('.composer textarea').value,'Draft survives navigation');w.document.querySelector('.send').click();await sleep(30);assert((await DB.all('chats')).some(c=>c.messages.some(m=>m.text==='Draft survives navigation')));closeApp(true);await sleep(25);
 openApp('settings');await sleep(30);assert(w.document.querySelector('.cloud-entry'));w.document.querySelector('.cloud-entry').click();await sleep(20);assert(w.document.querySelector('.cloud-panel'));closeApp(true);await sleep(25);
 openApp('photos');await sleep(20);assert(w.document.querySelector('.photo-nav button').textContent==='Select');assert(w.document.querySelector('.photo-add'));closeApp(true);await sleep(25);
 openApp('notes');await sleep(20);click('New note');const oldPut=DB.put;DB.put=async()=>null;ta=w.document.querySelector('.note-editor textarea');ta.value='Must not silently lose this';ta.dispatchEvent(new w.Event('input'));w.confirm=()=>false;closeApp(true);await sleep(30);assert(w.document.querySelector('.note-editor'),'failed save keeps editor open');DB.put=oldPut;closeApp(true);await sleep(30);assert(!w.document.querySelector('.note-editor'));assert((await DB.all('notes')).some(n=>n.text==='Must not silently lose this'));w.confirm=()=>true;
 openApp('calculator');await sleep(20);assert(w.document.querySelector('.calculator'));closeApp(true);
 dom.window.close();console.log('Whole app: Notes close/save + formatting + delete, Phone handoff, Messages draft/send, Settings/Cloud, Photos and Calculator passed');
})().catch(e=>{console.error(e);process.exit(1)});
