const assert=require('node:assert/strict'),fs=require('fs'),crypto=require('crypto');
const {indexedDB}=require('./node_modules/fake-indexeddb');
const {JSDOM}=require('./node_modules/jsdom');
global.crypto=crypto.webcrypto;
const {create}=require('../media-store.js');
const File=require('node:buffer').File;
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function main(){
 const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('large-media-test',1);r.onupgradeneeded=()=>{const s=r.result.createObjectStore('media',{keyPath:'id'});s.createIndex('createdAt','createdAt');r.result.createObjectStore('kv');};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
 const store=create(async()=>db);const files=Array.from({length:2100},(_,i)=>new File([new Uint8Array([i%256,10,22,33])],`media-${i}.${i%3?'jpg':'mp4'}`,{type:i%3?'image/jpeg':'video/mp4',lastModified:1000+i}));
 let beats=0;const timer=setInterval(()=>beats++,10),start=Date.now();let result=await store.importFiles(files);clearInterval(timer);assert.equal(result.saved,2100);assert.equal(result.failed.length,0);assert(beats>20);let meta=await store.scan();assert.equal(meta.length,2100);assert(!('blob' in meta[0]));
 for(const m of meta.slice(0,10)){const original=files.find(f=>f.name===m.name),saved=await store.get(m.id);assert.deepEqual(Buffer.from(await saved.blob.arrayBuffer()),Buffer.from(await original.arrayBuffer()));assert.equal(saved.blob.size,original.size);}
 result=await store.importFiles([files[0],new File(['DIFFERENT'],files[0].name,{type:'image/jpeg',lastModified:1000}),new File(['bad'],'bad.txt',{type:'text/plain'})]);assert.equal(result.saved,1);assert.equal(result.duplicates,1);assert.equal(result.failed.length,1);
 let stop=false;const unsubscribe=store.subscribe(s=>{if(s.running&&s.saved>=21&&!stop){stop=true;store.cancel();}});result=await store.importFiles(Array.from({length:100},(_,i)=>new File(['x'],`cancel-${i}.jpg`,{type:'image/jpeg'})));unsubscribe();assert(result.cancelled);assert(result.saved>=21&&result.saved<100);assert.equal((await store.lastJob()).running,false);
 // Same name/size/date with different bytes must never be silently skipped.
 result=await store.importFiles([new File(['abcd'],'collision.jpg',{type:'image/jpeg',lastModified:1}),new File(['efgh'],'collision.jpg',{type:'image/jpeg',lastModified:1})]);assert.equal(result.saved,2);
 console.log('2100 mixed imports: '+(Date.now()-start)+'ms; UI timer ticks '+beats+'; bytes, duplicate collision, failure isolation and interruption passed');
 const dom=new JSDOM('<div id="app"></div>',{runScripts:'outside-only',pretendToBeVisual:true,url:'https://test.local'}),w=dom.window;w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};w.confirm=()=>true;w.eval(fs.readFileSync('photos-ui.js','utf8'));
 const items=Array.from({length:5200},(_,i)=>({id:''+i,name:'image-'+i,kind:'image',size:10,createdAt:i,hasThumb:true}));const fake={scan:async()=>items,get:async id=>({...items[+id],thumb:new w.Blob(['x'])}),lastJob:async()=>null,subscribe:()=>()=>{},state:{running:false}};
 const root=w.document.querySelector('#app');const cleanup=w.LoftPhotos.mount({root,win:root,toast:()=>{}},fake);await delay(30);root.querySelector('.photo-nav button').click();root.querySelector('.selection-bar button').click();assert.match(root.querySelector('.photo-count').textContent,/5,200/);assert(root.querySelectorAll('.media-tile').length<150);const firstIds=[...root.querySelectorAll('.media-tile')].map(e=>e.getAttribute('aria-label'));const scroller=root.querySelector('.photo-scroll');scroller.scrollTop=50000;scroller.dispatchEvent(new w.Event('scroll'));await delay(30);assert(root.querySelectorAll('.media-tile').length<150);assert(!firstIds.includes(root.querySelector('.media-tile').getAttribute('aria-label')));cleanup();dom.window.close();console.log('5200 select-all and scrolled virtual grid: <150 tiles');
 let writes=0;const quotaDB={transaction(names,mode){if(mode==='readwrite'&&Array.isArray(names)&&names.includes('media')&&++writes===2)throw new DOMException('Quota','QuotaExceededError');return db.transaction(names,mode);}};
 const quota=create(async()=>quotaDB);const qfiles=[new File(['a'],'quota-a.jpg',{type:'image/jpeg'}),new File(['b'],'quota-b.jpg',{type:'image/jpeg'}),new File(['c'],'quota-c.jpg',{type:'image/jpeg'})];const qstate=await quota.importFiles(qfiles);assert.equal(qstate.saved,1);assert(qstate.cancelled);assert(qstate.failed[0].message.includes('full'));const retry=await quota.importFiles(qfiles);assert.equal(retry.saved,2);assert.equal(retry.duplicates,1);console.log('Quota failure preserves committed originals; reselect resumes without duplication');
 const large=new File([new Uint8Array(64*1024*1024)],'large-video.mp4',{type:'video/mp4',lastModified:7});assert.equal((await store.importFiles([large])).saved,1);const lm=(await store.scan()).find(m=>m.name==='large-video.mp4'),lr=await store.get(lm.id);assert.equal(lr.blob.size,large.size);assert.equal(crypto.createHash('sha256').update(Buffer.from(await lr.blob.arrayBuffer())).digest('hex'),crypto.createHash('sha256').update(Buffer.from(await large.arrayBuffer())).digest('hex'));console.log('64 MiB original preserved byte-for-byte (synthetic video payload, not codec playback)');
 const context={globalThis:null};context.globalThis=context;require('vm').runInNewContext(fs.readFileSync('sha256.js','utf8'),context);for(const size of [0,1,55,56,63,64,65,1024,1048576+13]){const bytes=crypto.randomBytes(size),h=new context.LoftSHA256();for(let i=0;i<size;i+=113)h.update(bytes.subarray(i,i+113));assert.equal(Buffer.from(h.digest()).toString('hex'),crypto.createHash('sha256').update(bytes).digest('hex'));}console.log('Incremental hashes match Node SHA-256 across block boundaries');
 await store.remove((await store.scan()).map(m=>m.id));assert.equal((await store.scan()).length,0);db.close();console.log('Batched bulk deletion passed');
}
main().catch(e=>{console.error(e);process.exit(1)});
